### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sadikoff** [sadikoff/i18n-form-bundle#4]
Hi all. I need some help with bundle. If you have some time to test it you are welcome! We need to find and fix all bugs and after it, we can start work on new features and optimizations.

My Task list is:
- [ ] More templates for more customization
- [ ] Simplify formField configuration 
- [ ] Use Twig autoconfiguration for form template

If you have any suggestions, I'll be happy to hear them.
